language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - secure: TDP3veLKvRvJ85YJjkTwvoVHPjKFi5AFJF38+q911GlfgxyReHs+2HX3KBk/ydb9kHC6lyadf3Jp+OwI+jefxEIfk4E2F/Z1ickCDvs0X/ZKAwIsvFIcAOslqTV0bKnan4M4xMZ9cwLStOhymZd2hpqMIrE/i4ZapJq0Y/n1/0lpJehfHkMqsVpDaNLrpFzZuFVUH9td2QR7GzE4jIzFy7/KKoFSt91qz4EPk9IJ4XpAQ2bvlK6WNXVuw9Wad23x7AqsfDia3rRyj3Ab45VnP/rvhl3rA+vHFo0VGkw+CH/AKwBlbKcbyTbsTJw+2es8a7B+ui/xbTj3hxevqn0idqxVHnqPOOZxQNCTy9GGHAg4iHpttgCa6NFsBc44jWLVLw9mDQXZF6iQ2D6V8PFBGsIJF4L4eL2K07w2Ysi3a81ql51H1lAjllxjU3Xq/DhNRN4A4Ng8QmM/SBeC+7+VgUG+VGcDX0Ok1m3PH1sUh1YJ/PW95qEOxghgyHs+KFYtIctsOohkV8Ici4TGeu2HhailYo0mD3x4TIEI0HFCzBJFoWMuer7JMHNErzFCvDmPM7PFY726rdKzEiiiYetqGm45bIsxgWmmuOcT/eNsc93ZPX19E6OldBixydYLgp5zJjikyRseUFHQ9FikyVE/2iNzYDeMMscCleCkd0wKo9Q=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
  -Dsonar.host.url=https://sonarqube.com
